# Generated by Django 6.0.6 on 2026-07-12 23:01

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def fix_zero_capacity(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')
    Room.objects.filter(capacity=0).update(capacity=1)


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='participants',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.RunPython(fix_zero_capacity, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='booking_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='room_capacity_positive'),
        ),
    ]
