# Generated by Django 6.0.6 on 2026-07-15 09:26

import django.contrib.postgres.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_busy_room_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('room', '='), (models.Func(models.F('start_time'), models.F('end_time'), function='tstzrange'), '&&')], name='exclude_overlapping_bookings'),
        ),
    ]
